devices([
	"iPhone SE",
	"iPhone 8",
	"iPhone 8 Plus",
        "iPhone 11 Pro",
	"iPhone 11 Pro Max",
	"iPad Pro (9.7-inch)",
	"iPad Pro (12.9-inch)"
])
languages([
  "en-GB",
  "en-US"
])
scheme("ReadingList_UITests")
workspace("ReadingList.xcworkspace")
clear_previous_screenshots(true)
reinstall_app(true)
concurrent_simulators(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["--reset", "--UITests", "--UITests_PopulateData", "--UITests_Screenshots", "-UIPreferredContentSizeCategoryName", "UICTContentSizeCategoryXL"])

# For more information about all available options run
# fastlane action snapshot
